name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        run: npm run build

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure Docker for insecure registry
        run: |
          echo '{"insecure-registries":["192.168.0.136:8082"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Log in to Nexus Docker registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 192.168.0.136:8082 -u "${{ secrets.NEXUS_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t 192.168.0.136:8082/demo-frontend:${{ github.run_number }} .
      - name: Push Docker image
        run: docker push 192.168.0.136:8082/demo-frontend:${{ github.run_number }}

  update-manifests:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifest repo
        uses: actions/checkout@v3
        with:
          repository: vasanthavijaya/manifest-repo
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
      - name: Update image tag
        run: |
          sed -i 's|image: 192.168.0.136:8082/demo-frontend:.*|image: 192.168.0.136:8082/demo-frontend:${{ github.run_number }}|' prod/deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add prod/deployment.yaml
          git commit -m "Update demo-frontend image to ${{ github.run_number }}"
          git push